// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/bg-compare/FrostLake.tsx": () => import("../components/mockups/bg-compare/FrostLake.tsx"),
  "./components/mockups/bg-compare/IceCave.tsx": () => import("../components/mockups/bg-compare/IceCave.tsx"),
  "./components/mockups/biz-profile/VerifiedProfile.tsx": () => import("../components/mockups/biz-profile/VerifiedProfile.tsx"),
  "./components/mockups/founding-badge/AchievementsCard.tsx": () => import("../components/mockups/founding-badge/AchievementsCard.tsx"),
  "./components/mockups/founding-badge/BadgeProfileHeader.tsx": () => import("../components/mockups/founding-badge/BadgeProfileHeader.tsx"),
  "./components/mockups/founding-badge/LeaderboardEntry.tsx": () => import("../components/mockups/founding-badge/LeaderboardEntry.tsx"),
  "./components/mockups/founding-badge/UpgradeBanner.tsx": () => import("../components/mockups/founding-badge/UpgradeBanner.tsx"),
  "./components/mockups/nav-preview/DevicesScreen.tsx": () => import("../components/mockups/nav-preview/DevicesScreen.tsx"),
  "./components/mockups/nav-preview/TimerScreen.tsx": () => import("../components/mockups/nav-preview/TimerScreen.tsx"),
  "./components/mockups/plunge-active/Current.tsx": () => import("../components/mockups/plunge-active/Current.tsx"),
  "./components/mockups/plunge-active/DeepGlow.tsx": () => import("../components/mockups/plunge-active/DeepGlow.tsx"),
  "./components/mockups/plunge-active/FocusMode.tsx": () => import("../components/mockups/plunge-active/FocusMode.tsx"),
  "./components/mockups/plunge-complete/CelebrationFirst.tsx": () => import("../components/mockups/plunge-complete/CelebrationFirst.tsx"),
  "./components/mockups/plunge-complete/ColdTakeReveal.tsx": () => import("../components/mockups/plunge-complete/ColdTakeReveal.tsx"),
  "./components/mockups/plunge-complete/Current.tsx": () => import("../components/mockups/plunge-complete/Current.tsx"),
  "./components/mockups/plunge-complete/HybridCombo.tsx": () => import("../components/mockups/plunge-complete/HybridCombo.tsx"),
  "./components/mockups/plunge-complete/LevelUp.tsx": () => import("../components/mockups/plunge-complete/LevelUp.tsx")
};
