// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/biz-profile/VerifiedProfile.tsx": () => import("../components/mockups/biz-profile/VerifiedProfile.tsx"),
  "./components/mockups/founding-badge/AchievementsCard.tsx": () => import("../components/mockups/founding-badge/AchievementsCard.tsx"),
  "./components/mockups/founding-badge/BadgeProfileHeader.tsx": () => import("../components/mockups/founding-badge/BadgeProfileHeader.tsx"),
  "./components/mockups/founding-badge/LeaderboardEntry.tsx": () => import("../components/mockups/founding-badge/LeaderboardEntry.tsx"),
  "./components/mockups/founding-badge/UpgradeBanner.tsx": () => import("../components/mockups/founding-badge/UpgradeBanner.tsx")
};
