export const COLD_TAKES: string[] = [
  "Your therapist is cheaper than this.",
  "You paid money to feel like this.",
  "Polar bears are laughing at you.",
  "Wim Hof would be proud. Your toes wouldn't.",
  "Discomfort is a feature, not a bug.",
  "Your ancestors hunted mammoths. You can survive this.",
  "The seals are watching. Don't embarrass them.",
  "Hypothermia is just enlightenment in disguise.",
  "Your warm bed misses you.",
  "Penguins do this for fun. Penguins.",
  "This is cheaper than a gym membership. Probably.",
  "Your body is begging you to stop. Your ego said no.",
  "Coffee is going to taste incredible after this.",
  "The shrinkage is temporary. The bragging rights are forever.",
  "If your friends could see you now, they'd call 911.",
  "Breathe. Or hyperventilate. Either works.",
  "This is what 'character building' actually looks like.",
  "The water is fine. Your nervous system disagrees.",
  "You're not freezing. You're optimizing.",
  "Goggins is watching. Don't disappoint him.",
  "Your future self thanks you. Your current self does not.",
  "Cold is just spicy temperature.",
  "Plot twist: the cold doesn't get easier. You get colder.",
  "Your skin is screaming. Ignore it.",
  "This counts as a personality trait now.",
  "Hot tubs are for the weak. (We're kidding. Hot tubs are great.)",
  "Numb is the new euphoric.",
  "Somewhere, your cardiologist is nervous.",
  "Pain is just weakness leaving the body. Through your skin.",
  "Your mitochondria are doing pull-ups right now.",
  "Brown fat says hi.",
  "This is legal in 50 states. Surprisingly.",
  "Your body has 99 problems. Heat ain't one.",
  "The Vikings did this without timers.",
  "Suffering, but make it aesthetic.",
  "Your dopamine receptors are about to throw a party.",
  "Norepinephrine has entered the chat.",
  "You will romanticize this later.",
  "This is the most expensive way to feel alive.",
  "Your shower will feel like Hawaii.",
  "Your body is 60% water. Most of it is now ice.",
  "You're basically a popsicle with goals.",
  "Even the fish are confused by your choices.",
  "This is what 'mind over matter' costs.",
  "Your significant other thinks you're crazy. They're right.",
  "The internet told you to do this. The internet was right.",
  "You're paying premium for goosebumps.",
  "Frostbite is just a rumor.",
  "This is more efficient than therapy. Almost.",
  "Your insurance doesn't cover this. Probably.",
  "You're not cold. You're recalibrated.",
  "Tomorrow you'll do this again. Why.",
  "Ice baths: because regular baths are too easy.",
  "Your testicles have retreated. They will return.",
  "You signed up for this. Voluntarily.",
  "Cold plungers don't die. They just freeze in time.",
  "The cold doesn't care about your feelings.",
  "Your nervous system filed a complaint.",
  "You came here to suffer beautifully.",
  "The cold is undefeated. You're 0-247.",
  "If you can read this, you're not focused enough.",
  "Your shivering is involuntary. Your suffering is voluntary.",
  "Welcome to the longest 60 seconds of your life.",
  "Time moves slower in cold water. Einstein-ish.",
  "This is the only meeting you can't leave early.",
  "You're not late. You're acclimating.",
  "Cold water teaches patience. Loudly.",
  "Your toes have left the chat.",
  "The cold builds character. And resentment.",
  "Sauna later? You've earned it.",
  "This will make a great Instagram story. Eventually.",
  "Your phone is dry. Be jealous.",
  "Cold plungers: the only people who pay to be uncomfortable.",
  "Adventure is just suffering with good lighting.",
  "Don't think about the warm shower. Don't.",
  "Your dignity exited at minute one.",
  "You're not crazy. You're committed.",
  "This is how you become unrelatable at parties.",
  "Cold immersion: because life wasn't hard enough.",
  "Even the ice cubes are concerned.",
  "Your hair follicles are filing a union complaint.",
  "Goosebumps: nature's bubble wrap.",
  "This is the cheapest natural high. Sort of.",
  "Your discomfort tolerance just leveled up.",
  "Cold water doesn't negotiate.",
  "You volunteered as tribute.",
  "Your blood vessels are doing yoga.",
  "Vasoconstriction is a vibe.",
  "Your body is now a science experiment.",
  "Welcome to the cult. The very cold cult.",
  "You'll feel amazing in 4 hours. Probably.",
  "Pain is information. The information is 'you're cold.'",
  "Don't look down. Just don't.",
  "Your sympathetic nervous system is awake. Very awake.",
  "Fight or flight? You chose 'sit very still.'",
  "Cold plunging: turning hot water into a luxury.",
  "Your bath bombs will never satisfy you again.",
  "The cold remembers your weaknesses.",
  "Hypothermia builds character. We think.",
  "Your inner monologue just learned new words.",
  "This is more focus than you've had all week.",
  "Cold immersion: 1, your comfort zone: 0.",
  "Embrace the suck. Literally.",
  "Your spirit animal is now an ice cube.",
  "You are one with the freezer aisle.",
  "Your face is doing things. Weird things.",
  "Even the polar bears would tap out.",
  "Cold water is the world's loudest meditation.",
  "Welcome to the worst spa day ever.",
  "Your immune system just got a software update.",
  "Inflammation? Never heard of her.",
  "Your aches and pains are also confused.",
  "The cold is free therapy. The plunge isn't.",
  "Look at you, doing the thing.",
  "Your tolerance is a renewable resource.",
  "You're more durable than yesterday.",
  "Future you is high-fiving present you.",
  "Cold doesn't build character. It reveals it.",
  "This is humility, served cold.",
  "Your ego doesn't fit in this tub.",
  "Quit and a polar bear loses its wings.",
  "Just 30 more seconds. (We're lying.)",
  "Almost done. (Also lying.)",
  "You're crushing it. Or being crushed. Same thing.",
  "The discomfort is the dividend.",
  "Cold water: the original biohack.",
  "Your stress hormones are getting a workout.",
  "Cortisol who?",
  "You will sleep like a stone tonight.",
  "REM sleep is rooting for you.",
  "Your skin will glow. Eventually. Maybe.",
  "Collagen, but at what cost.",
  "This is why your friends stopped inviting you to brunch.",
  "Sunday Funday looks different now.",
  "Your hobbies are concerning.",
  "Healthy? Insane? Why not both.",
  "This is what 'optimizing' looks like.",
  "Your morning routine is a war crime.",
  "Marines train less than this.",
  "Navy SEALs respect you. From a heated room.",
  "You're harder than the average person. And colder.",
  "Soft life? Never heard of her.",
  "Comfort is the enemy. (Comfort is also great.)",
  "Your discomfort threshold just signed for overtime.",
  "Resilience: now in a tub near you.",
  "This is what voluntary hardship feels like.",
  "Stoicism, but make it wet.",
  "Marcus Aurelius would approve.",
  "The Spartans would be impressed.",
  "You are the bear. The bear is you.",
  "Bear mode: activated.",
  "You're not built different. You're built colder.",
  "Frozen, but make it fashion.",
  "Ice in your veins. Literally.",
  "Cold blood is a personality trait.",
  "Your warm-blooded friends don't understand.",
  "Mammalian instincts: overridden.",
  "Reptile mode: engaged.",
  "Your reflection in the water is judging you.",
  "Even the water is uncomfortable.",
  "The thermometer is lying. It's colder.",
  "Your toes don't believe in you anymore.",
  "Toes? What toes.",
  "Fingers? Optional.",
  "Sensation is overrated.",
  "Numbness is just advanced toughness.",
  "Your nipples have entered another dimension.",
  "The cold has consumed your nipples. They are home now.",
  "Don't look at the goosebumps. They'll multiply.",
  "Your hair stood up to applaud you.",
  "Even your skin is impressed.",
  "Pores: officially closed for business.",
  "Sebum production: halted.",
  "Cold water is a free facial. Sort of.",
  "Your dermatologist is somewhere nodding.",
  "Spa day, but make it military.",
  "Self-care, but extreme.",
  "Wellness, but make it hurt.",
  "Your wellness journey is now a war.",
  "Mindfulness, but at 38 degrees.",
  "Meditation, but the floor is lava. Cold lava.",
  "Breathe in. Breathe out. Don't scream.",
  "Box breathing? More like ice cube breathing.",
  "Wim Hof breathing intensifies.",
  "Your CO2 tolerance is leveling up.",
  "Your O2 saturation is showing off.",
  "Your lungs are confused but trying.",
  "Diaphragm: working overtime.",
  "Your vagus nerve is having a moment.",
  "Vagal tone: maximized.",
  "Heart rate variability says hello.",
  "Your heart just took a deep breath.",
  "Cardiovascular system: tested.",
  "Your circulation is now top-tier.",
  "Blood flow: optimized.",
  "Your extremities have left a strongly worded note.",
  "Capillaries: doing the most.",
  "Peripheral vasoconstriction is poetry.",
  "Your body is rerouting traffic. To survive.",
  "Core temperature: protected.",
  "Your organs are huddling.",
  "Your kidneys are tired.",
  "Your bladder has thoughts.",
  "You will pee. It's science.",
  "The cold diuresis is real.",
  "Pee now or forever hold your peace.",
  "Even your gut bacteria are shivering.",
  "Microbiome: in distress.",
  "Your gut feels seen.",
  "Vagal stimulation, served cold.",
  "Your parasympathetic system is napping. Rudely.",
  "Calm? In this economy?",
  "Your nervous system is renegotiating its contract.",
  "Adrenal glands: working from home no more.",
  "Cortisol cosplay.",
  "Stress test passed. With shivering.",
  "Your hormones are confused but loyal.",
  "Testosterone: rumored to increase.",
  "Estrogen: also vibing.",
  "Your endocrine system is taking notes.",
  "Pituitary gland: surprised.",
  "Hypothalamus: working harder than you.",
  "Thermoregulation is a full-time job.",
  "Your hypothalamus deserves a raise.",
  "Set point: rudely shifted.",
  "Homeostasis: temporarily disrupted.",
  "Your baseline just moved.",
  "You're rewiring yourself. Literally.",
  "Neuroplasticity: now in a tub.",
  "Your brain is making new friends.",
  "BDNF: rumored to be present.",
  "Your dopamine receptors are doing CrossFit.",
  "Serotonin: maybe?",
  "Your mood is about to be unreasonably good.",
  "Post-plunge euphoria is real. Hold on.",
  "The afterglow is worth it.",
  "Trust the process. The cold, cold process.",
  "Type 2 fun is the only fun.",
  "This is fun. We promise.",
  "You're having fun, right? Right?",
  "Fun is relative. So is comfort.",
  "Your definition of fun has evolved.",
  "Your weekend plans are concerning.",
  "Normal people are eating pancakes right now.",
  "Normal people are sleeping in.",
  "Normal people are warm.",
  "You chose violence.",
  "You chose chaos.",
  "You chose to feel everything at once.",
  "The chaos is the point.",
  "Your nervous system needs chaos to grow.",
  "Discomfort is the teacher. The cold is the classroom.",
  "School is in session.",
  "Pop quiz: how long can you stay?",
  "Final exam: just don't leave.",
  "Graduation requires shivering.",
  "PhD in suffering, with honors.",
  "Your transcript reads: plunged. shivered. survived.",
  "Add this to your resume. They'll have questions.",
  "Skills section: cold tolerance.",
  "LinkedIn isn't ready for this.",
  "Your hobbies are now a personality.",
  "You will tell everyone about this. They will not care.",
  "Save the lecture for after the plunge.",
  "Less talking. More shivering.",
  "Focus. Breathe. Suffer.",
  "Three rules: shut up, breathe, stay in.",
  "The cold doesn't care about your podcast.",
  "The cold doesn't care about your routine.",
  "The cold doesn't care, period.",
  "You're alone with the cold now.",
  "The cold is your therapist now.",
  "Tell the cold your problems. It won't listen.",
  "The cold heard you. The cold doesn't care.",
  "Acceptance is the only exit.",
  "Resistance is futile. Also painful.",
  "Surrender. To the cold. Not the timer.",
  "The timer is your friend. The cold is not.",
  "Watch the timer. Pretend it moves.",
  "Time is a flat circle. A frozen one.",
  "Einstein was right. Time is relative. In cold.",
  "A minute here is a year anywhere else.",
  "Patience is a cold-blooded virtue.",
  "Stillness is everything.",
  "Move and you'll feel it more.",
  "Move and the cold notices you.",
  "Stay still. The cold gets bored.",
  "Be the rock. The cold rock.",
  "Be the iceberg, not the Titanic.",
  "Sink with grace.",
  "Float with intention.",
  "Breathe through your nose. Or just panic. Either way.",
  "Don't gasp. Don't gasp. You gasped.",
  "Cold shock response: 1, you: 0.",
  "The first 15 seconds are the worst. Probably.",
  "The first minute is the worst. Definitely.",
  "Every minute is the worst, actually.",
  "You're doing great. We're being honest.",
  "You're doing terribly. We're being honest.",
  "We don't actually know how you're doing.",
  "Only you know how cold you are.",
  "Only you know why you're here.",
  "Remind yourself why you're here.",
  "Was it the dopamine? Was it the discipline?",
  "Was it the TikTok? Be honest.",
  "Whatever it was, you're committed now.",
  "Halfway done. Maybe. Probably not.",
  "Don't check the timer. You'll be sad.",
  "Don't check the temperature. You'll be sadder.",
  "Ignorance is warmth.",
  "What you don't know can still freeze you.",
  "Acceptance, but make it shivering.",
  "Gratitude practice: be grateful you can leave.",
  "Some people live in this temperature year-round.",
  "Some people have it worse. Probably.",
  "Perspective: also frozen.",
  "Your problems shrink in cold water.",
  "Your problems also literally shrink.",
  "Everything shrinks in cold water.",
  "Your worldview is now smaller and colder.",
  "Stoic mode: activated.",
  "Memento mori, but make it wet.",
  "You will die one day. Not today. Probably.",
  "The cold reminds you you're alive.",
  "Aliveness has a price. The price is shivering.",
  "Worth it. Probably.",
  "You're going to do this again tomorrow.",
  "You said you wouldn't. You will.",
  "The cold has you now.",
  "Welcome to the addiction.",
  "First plunge is free. After that, it's $19.99.",
  "Cold water is a gateway drug.",
  "Soon you'll be doing this in the ocean.",
  "Soon you'll be doing this in winter.",
  "Soon you'll be that person.",
  "You are now that person.",
  "Accept it. You're a cold plunger now.",
  "Embrace the identity. Embrace the cold.",
  "You're built for this. Sort of.",
  "You can do hard things. This is one of them.",
  "Hard things make easy things easier.",
  "The cold is preparation. For everything.",
  "Bad day at work? Cold plunge prepared you.",
  "Awkward dinner? Cold plunge prepared you.",
  "Existential dread? Cold plunge prepared you.",
  "You are immune to small discomforts now.",
  "Cold showers feel warm. That's not normal.",
  "Your standards for cold have shifted.",
  "Your tolerance is now your superpower.",
  "Your superpower is sitting in cold water.",
  "Spider-Man got bitten. You got cold.",
  "Origin story: ice tub.",
  "Cape: not waterproof.",
  "Hero pose: shivering.",
  "Sidekick: a thermometer.",
  "Villain: warm water.",
  "Nemesis: the urge to leave.",
  "Final boss: the last 30 seconds.",
  "Boss fight in progress.",
  "Stay in the fight.",
  "Don't tap out. You're winning.",
  "You're winning. We can't prove it, but vibes.",
  "Vibes are immaculate. Despite the shivering.",
  "Cold and unbothered.",
  "Cold and thriving.",
  "Cold and slightly concerned.",
  "Cold and rethinking life choices.",
  "Life choices: questionable. Plunge: legendary.",
];
